buildscript {
    repositories {
        maven { url = 'https://maven.minecraftforge.net/' }
        mavenCentral()
    }
    dependencies {
        classpath 'net.minecraftforge.gradle:ForgeGradle:3.+'
    }
}
apply plugin: 'net.minecraftforge.gradle'

version = '0.2.0'
group = 'com.dogpound.pridecarts'
archivesBaseName = 'PrideCarts-1.12.2'
sourceCompatibility = targetCompatibility = compileJava.sourceCompatibility = compileJava.targetCompatibility = '1.8'

minecraft {
    mappings channel: 'snapshot', version: '20171003-1.12'
}

repositories { mavenCentral() }

dependencies {
    minecraft 'net.minecraftforge:forge:1.12.2-14.23.5.2860'
    compileOnly files('libs/mixinbooter-api.jar')
    compileOnly files('libs/sponge-mixin.jar')
    compileOnly files('libs/railcraft.jar')     // optional: trains = Railcraft's linked carts when it's installed
}


jar.finalizedBy('reobfJar')
